/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Libb;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author palsa
 */
public class BookList extends javax.swing.JFrame {

    Connection con;
    PreparedStatement par;
    ResultSet rs;
    public BookList() {
        initComponents();
        Connect();
        BookList();
    }
public void Connect()
{
    try{
        Class.forName("com.mysql.cj.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pallavi","root","Dreams");   
        } 
    catch (Exception ex) {
        ex.printStackTrace();
    }
}

/// Insert data into table code here  

public void BookList()
    {
        int c;
        try
        {
            par=con.prepareStatement("select * from BookList");
            rs=par.executeQuery();
            ResultSetMetaData rad =rs.getMetaData();
            c=rad.getColumnCount();
            DefaultTableModel d= (DefaultTableModel)jTable1.getModel();
            d.setRowCount(0);
            while(rs.next()){
            Vector v =new Vector();
            for(int i=1;i<=c;i++){
                v.add(rs.getString("Bid"));
                v.add(rs.getString("Bname"));
                v.add(rs.getString("Aname"));
                v.add(rs.getString("Bcourse"));
                v.add(rs.getString("BSNo"));
                v.add(rs.getString("Department"));
                v.add(rs.getString("NofPages"));
            }
            d.addRow(v);
        }
        } catch (SQLException ex) {
           ex.printStackTrace();
        }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtName = new javax.swing.JLabel();
        txtRollNo = new javax.swing.JLabel();
        txtCourse = new javax.swing.JLabel();
        txtClass = new javax.swing.JLabel();
        txtBranch = new javax.swing.JLabel();
        txtMob = new javax.swing.JLabel();
        BName = new javax.swing.JTextField();
        AName = new javax.swing.JTextField();
        BCourse = new javax.swing.JTextField();
        BSerNo = new javax.swing.JTextField();
        Depart = new javax.swing.JTextField();
        NOP = new javax.swing.JTextField();
        BDetailSub1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        UpdateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        CancleButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        BBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setMaximumSize(new java.awt.Dimension(1518, 732));
        jPanel2.setMinimumSize(new java.awt.Dimension(1518, 732));
        jPanel2.setPreferredSize(new java.awt.Dimension(1518, 732));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);

        txtName.setBackground(new java.awt.Color(0, 51, 102));
        txtName.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtName.setText("Book Name");
        txtName.setOpaque(true);

        txtRollNo.setBackground(new java.awt.Color(0, 51, 102));
        txtRollNo.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        txtRollNo.setForeground(new java.awt.Color(255, 255, 255));
        txtRollNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRollNo.setText("Author ");
        txtRollNo.setOpaque(true);

        txtCourse.setBackground(new java.awt.Color(0, 51, 102));
        txtCourse.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        txtCourse.setForeground(new java.awt.Color(255, 255, 255));
        txtCourse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCourse.setText("Course");
        txtCourse.setOpaque(true);

        txtClass.setBackground(new java.awt.Color(0, 51, 102));
        txtClass.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        txtClass.setForeground(new java.awt.Color(255, 255, 255));
        txtClass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtClass.setText("Serial No");
        txtClass.setOpaque(true);

        txtBranch.setBackground(new java.awt.Color(0, 51, 102));
        txtBranch.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        txtBranch.setForeground(new java.awt.Color(255, 255, 255));
        txtBranch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBranch.setText("Department");
        txtBranch.setOpaque(true);

        txtMob.setBackground(new java.awt.Color(0, 51, 102));
        txtMob.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        txtMob.setForeground(new java.awt.Color(255, 255, 255));
        txtMob.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMob.setText("Total Pages");
        txtMob.setOpaque(true);

        BName.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        BName.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                BNameKeyPressed(evt);
            }
        });

        AName.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N

        BCourse.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N

        BSerNo.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N

        Depart.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N

        NOP.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N

        BDetailSub1.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        BDetailSub1.setForeground(new java.awt.Color(0, 51, 102));
        BDetailSub1.setText("Submit");
        BDetailSub1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BDetailSub1ActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String []
            {
                "Id", "Book Name", "Author Name", "Course", "Serial No", "Department", "No of page"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }
        });
        jTable1.setToolTipText("");
        jTable1.setGridColor(new java.awt.Color(204, 204, 255));
        jTable1.setRowHeight(30);
        jTable1.setShowGrid(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0)
        {
            jTable1.getColumnModel().getColumn(0).setMinWidth(20);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        UpdateButton.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        UpdateButton.setForeground(new java.awt.Color(0, 51, 102));
        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                UpdateButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(0, 51, 102));
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                deleteButtonActionPerformed(evt);
            }
        });

        CancleButton.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        CancleButton.setForeground(new java.awt.Color(0, 51, 102));
        CancleButton.setText("Cancel");
        CancleButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CancleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 986, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BDetailSub1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(CancleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBranch, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BName)
                            .addComponent(BCourse, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Depart, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMob, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(txtClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtRollNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NOP, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                            .addComponent(BSerNo)
                            .addComponent(AName))
                        .addGap(64, 64, 64))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtRollNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BSerNo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtClass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Depart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtMob, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NOP, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(7, 7, 7)))
                    .addComponent(txtBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(BDetailSub1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deleteButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                            .addComponent(UpdateButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(CancleButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(278, 278, 278))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, 510));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 43)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Book-List Details");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 380, 90));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1892, 39, -1, -1));

        BBack.setBackground(new java.awt.Color(0, 51, 102));
        BBack.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        BBack.setForeground(new java.awt.Color(255, 255, 255));
        BBack.setText("Back");
        BBack.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BBackActionPerformed(evt);
            }
        });
        jPanel2.add(BBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 100, 35));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Libb/background.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(1518, 732));
        jLabel2.setMinimumSize(new java.awt.Dimension(1518, 732));
        jLabel2.setPreferredSize(new java.awt.Dimension(1518, 732));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1520, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BDetailSub1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDetailSub1ActionPerformed
        // TODO add your handling code here:
        String Bname=BName.getText();
        String Aname= AName.getText();
        String Bcourse =BCourse.getText();
        String Bserno=BSerNo.getText();
        String depart= Depart.getText();
        String nop= NOP.getText();
        //Validation 
       // String Book=BName.getText();
    if (!Pattern.matches("[a-zA-Z]*",Bname)) { 
  JOptionPane.showMessageDialog(this,"Book name Invalid");
   BName.setText("");
    
    BName.requestFocus();
  
}
    // String Author=AName.getText();
    else if (!Pattern.matches("[a-zA-Z]+"+" "+"[a-zA-Z]+",Aname)) { 
  JOptionPane.showMessageDialog(this,"Invalid Author Name");
   AName.setText("");
    
    AName.requestFocus();
  
}
     //String course = BCourse.getText();
   else if (!Pattern.matches("[a-zA-Z]+",Bcourse)) { 
  JOptionPane.showMessageDialog(this,"Invalid Course Name");
   BCourse.setText("");
    
    BCourse.requestFocus();
  
}
     //String SerNo=BSerNo.getText();
   else if (!Pattern.matches("[0-9]+",Bserno)) { 
  JOptionPane.showMessageDialog(this,"Invalid Serial No");
   BSerNo.setText("");
    
    BSerNo.requestFocus();
  
}
    //String det=Depart.getText();
   else if (!Pattern.matches("[a-zA-Z]+",depart)) { 
  JOptionPane.showMessageDialog(this,"Invalid Department No");
   Depart.setText("");
    
    Depart.requestFocus();
}
     //String Pages=NOP.getText();
   else if (!Pattern.matches("[0-9]+",nop)) { 
  JOptionPane.showMessageDialog(this,"Invalid Page No");
   NOP.setText("");
    
    NOP.requestFocus();
    }
    else {
        try {
            par =con.prepareStatement("Insert into BookList(Bname,Aname,Bcourse,BSNo,Department,NofPages)values(?,?,?,?,?,?)");
            
            par.setString(1,Bname);
            par.setString(2,Aname);
            par.setString(3,Bcourse);
            par.setString(4,Bserno);
            par.setString(5,depart);
            par.setString(6,nop);
            int s=par.executeUpdate();
        
        if(s==1)
        {
            JOptionPane.showMessageDialog(this ," Book Details Submitted");
            
            BName.setText("");
            AName.setText("");
            BCourse.setText("");
            BSerNo.setText("");
            Depart.setText("");
            NOP.setText("");
            BName .requestFocus();
            BookList();
            BDetailSub1.setEnabled(true);
            
        }
        else
        {
              JOptionPane.showMessageDialog(this ,"Errror");
        }
        
        
        } catch (SQLException ex) {
           ex.printStackTrace();
        }
        }
  
    }//GEN-LAST:event_BDetailSub1ActionPerformed

    private void BBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBackActionPerformed
        this.setVisible(false); 
    }//GEN-LAST:event_BBackActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         DefaultTableModel d1= (DefaultTableModel)jTable1.getModel();
         int selectIndex =jTable1.getSelectedRow();
         int BookId= Integer.parseInt( d1.getValueAt(selectIndex,0).toString());
        // String  StudentName =(String) d1.getValueAt(selectIndex,0);
        BName.setText( d1.getValueAt(selectIndex,1).toString());
         
          AName.setText( d1.getValueAt(selectIndex,2).toString());
         BCourse.setText( d1.getValueAt(selectIndex,3).toString());
         BSerNo.setText( d1.getValueAt(selectIndex,4).toString());
         Depart.setText( d1.getValueAt(selectIndex,5).toString());
         NOP.setText( d1.getValueAt(selectIndex,6).toString());
         BDetailSub1.setEnabled(false);
        // Reset.setEnabled(false);
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
         DefaultTableModel d1= (DefaultTableModel)jTable1.getModel();
         int selectIndex =jTable1.getSelectedRow();
         
        // String  StudentName =(String) d1.getValueAt(selectIndex,0);
        int BookId= Integer.parseInt( d1.getValueAt(selectIndex,0).toString());
        String Bname=BName.getText();
        String Aname= AName.getText();
        String Bcourse =BCourse.getText();
        String Bserno =BSerNo.getText();
        String depart= Depart.getText();
        String nop= NOP.getText();
        
        try {
            par =con.prepareStatement("update BookList set Bname=?,Aname=?,Bcourse=?,BSNo=?,Department=?,NofPages=? where Bid = ?");
             
            par.setString(1,Bname);
            par.setString(2,Aname);
        par.setString(3,Bcourse);
        par.setString(4,Bserno);
        par.setString(5,depart);
        par.setString(6,nop);
        par.setInt(7,BookId); 
        int s=par.executeUpdate();
        if(s==1)
        {
            JOptionPane.showMessageDialog(this ,"BookList updated");
            BName.setText("");
            AName.setText("");
            BCourse.setText("");
            BSerNo.setText("");
            Depart.setText("");
            NOP.setText("");
            
            BName.requestFocus();
            BookList();
                }
        else
        {
              JOptionPane.showMessageDialog(this ,"Errror");
        }
        
        
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel d1= (DefaultTableModel)jTable1.getModel();
         int selectIndex =jTable1.getSelectedRow();
         
       
        int BookId= Integer.parseInt( d1.getValueAt(selectIndex,0).toString());

        
        try {
            par =con.prepareStatement("Delete from BookList where Bid = ?");
             

        par.setInt(1,BookId); 
        int s=par.executeUpdate();
        
        if(s==1)
        {
            JOptionPane.showMessageDialog(this ,"Book Deleted");
             
            BName.setText("");
            AName.setText("");
            BCourse.setText("");
            BSerNo.setText("");
            Depart.setText("");
            NOP.setText("");
            
            BName.requestFocus();
            BookList();
            BDetailSub1.setEnabled(true);
        }
        else
        {
              JOptionPane.showMessageDialog(this ,"Errror");
        }
        
        
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void CancleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancleButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_CancleButtonActionPerformed

    private void BNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BNameKeyPressed
    }//GEN-LAST:event_BNameKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AName;
    private javax.swing.JButton BBack;
    private javax.swing.JTextField BCourse;
    private javax.swing.JButton BDetailSub1;
    private javax.swing.JTextField BName;
    private javax.swing.JTextField BSerNo;
    private javax.swing.JButton CancleButton;
    private javax.swing.JTextField Depart;
    private javax.swing.JTextField NOP;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel txtBranch;
    private javax.swing.JLabel txtClass;
    private javax.swing.JLabel txtCourse;
    private javax.swing.JLabel txtMob;
    private javax.swing.JLabel txtName;
    private javax.swing.JLabel txtRollNo;
    // End of variables declaration//GEN-END:variables
}
