
package Libb;

public class MainPage extends javax.swing.JFrame {

    public MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel3 = new javax.swing.JPanel();
        newStu = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        StuList = new javax.swing.JButton();
        BookList = new javax.swing.JButton();
        out = new javax.swing.JButton();
        SearchStu = new javax.swing.JButton();
        IssueBook = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1600, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setMaximumSize(new java.awt.Dimension(1518, 732));
        jPanel3.setMinimumSize(new java.awt.Dimension(1518, 732));
        jPanel3.setPreferredSize(new java.awt.Dimension(1518, 732));
        jPanel3.setLayout(null);

        newStu.setBackground(new java.awt.Color(0, 51, 102));
        newStu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newStu.setForeground(new java.awt.Color(255, 255, 255));
        newStu.setText("New Student");
        newStu.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                newStuActionPerformed(evt);
            }
        });
        jPanel3.add(newStu);
        newStu.setBounds(360, 150, 190, 50);

        Back.setBackground(new java.awt.Color(204, 255, 255));
        Back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Back.setForeground(new java.awt.Color(0, 51, 102));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BackActionPerformed(evt);
            }
        });
        jPanel3.add(Back);
        Back.setBounds(40, 20, 90, 40);

        StuList.setBackground(new java.awt.Color(0, 51, 102));
        StuList.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        StuList.setForeground(new java.awt.Color(255, 255, 255));
        StuList.setText("Students List");
        StuList.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                StuListActionPerformed(evt);
            }
        });
        jPanel3.add(StuList);
        StuList.setBounds(360, 220, 190, 50);

        BookList.setBackground(new java.awt.Color(0, 51, 102));
        BookList.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BookList.setForeground(new java.awt.Color(255, 255, 255));
        BookList.setText("Book List");
        BookList.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BookListActionPerformed(evt);
            }
        });
        jPanel3.add(BookList);
        BookList.setBounds(640, 150, 190, 50);

        out.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        out.setForeground(new java.awt.Color(0, 51, 102));
        out.setText("logOut");
        out.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                outActionPerformed(evt);
            }
        });
        jPanel3.add(out);
        out.setBounds(520, 530, 130, 50);

        SearchStu.setBackground(new java.awt.Color(0, 51, 102));
        SearchStu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SearchStu.setForeground(new java.awt.Color(255, 255, 255));
        SearchStu.setText("Search student");
        SearchStu.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SearchStuActionPerformed(evt);
            }
        });
        jPanel3.add(SearchStu);
        SearchStu.setBounds(360, 290, 190, 50);

        IssueBook.setBackground(new java.awt.Color(0, 51, 102));
        IssueBook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IssueBook.setForeground(new java.awt.Color(255, 255, 255));
        IssueBook.setText("Isssue Book");
        IssueBook.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                IssueBookActionPerformed(evt);
            }
        });
        jPanel3.add(IssueBook);
        IssueBook.setBounds(640, 220, 190, 50);

        jButton1.setBackground(new java.awt.Color(0, 51, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Library Managemnt App");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(360, 20, 470, 54);

        jLabel1.setText("jLabel1");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(550, 60, 37, 16);

        jButton2.setBackground(new java.awt.Color(0, 51, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Return Books");
        jButton2.setToolTipText("");
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(640, 290, 190, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Libb/background.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(0, 0, 1518, 732);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1518, 732));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void newStuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStuActionPerformed
        // TODO add your handling code here:
       
       NewStudentDetails ns =new NewStudentDetails();
       ns.setVisible(true);
    }//GEN-LAST:event_newStuActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
            new ALogin().setVisible(true);
            dispose();// TODO add your handling code here:
    }//GEN-LAST:event_BackActionPerformed

    private void IssueBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssueBookActionPerformed
        // TODO add your handling code here:
        IssueBook ib =new IssueBook();
        ib.setVisible(true);
    }//GEN-LAST:event_IssueBookActionPerformed

    private void BookListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookListActionPerformed
        // TODO add your handling code here:
        BookList bl =new BookList();
        bl.setVisible(true);
    }//GEN-LAST:event_BookListActionPerformed

    private void StuListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StuListActionPerformed
        // TODO add your handling code here:
        StudentList sl =new StudentList();
        sl.setVisible(true);
    }//GEN-LAST:event_StuListActionPerformed

    private void SearchStuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchStuActionPerformed
        // TODO add your handling code here:
        searchStudent1 ss =new searchStudent1();
        ss.setVisible(true);
    }//GEN-LAST:event_SearchStuActionPerformed

    private void outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outActionPerformed
        // TODO add your handling code here:
        ALogin al =new ALogin();
        this.hide();
        al.setVisible(true);
    }//GEN-LAST:event_outActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        BookReturn br = new BookReturn();
         br.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton BookList;
    private javax.swing.JButton IssueBook;
    private javax.swing.JButton SearchStu;
    private javax.swing.JButton StuList;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton newStu;
    private javax.swing.JButton out;
    // End of variables declaration//GEN-END:variables
}
