
package Libb;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

public class NewStudentDetails extends javax.swing.JFrame
{
    Connection con;
    PreparedStatement par;
    ResultSet rs;
    public NewStudentDetails()
    {
        initComponents();
         Connect();
         StudentList();
    }
    public void Connect()
    {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pallavi","root","Dreams");   
        } 
        catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    public void StudentList(){
    int c;
        try {
            par=con.prepareStatement("select * from newstudent");
            rs=par.executeQuery();
            
            ResultSetMetaData rad =rs.getMetaData();
            c=rad.getColumnCount();
            while(rs.next()){
            Vector v =new Vector();
            for(int i=1;i<=c;i++){
                v.add(rs.getString("SNo"));
                v.add(rs.getString("SName"));
                v.add(rs.getString("SRollNo"));
                v.add(rs.getString("SCourse"));
                v.add(rs.getString("SBranch"));
                v.add(rs.getString("SMob"));
                }
            }
            } 
        catch (Exception ex) {
            ex.printStackTrace();
            }
        }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtRollNo = new javax.swing.JTextField();
        txtMobNo = new javax.swing.JTextField();
        txtBranch = new javax.swing.JTextField();
        txtCourse = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1518, 732));
        getContentPane().setLayout(null);

        jLabel2.setBackground(new java.awt.Color(0, 51, 102));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" New Student Details");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(540, 60, 290, 40);

        jLabel1.setBackground(new java.awt.Color(0, 51, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("   Name");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(460, 160, 110, 40);

        jLabel3.setBackground(new java.awt.Color(0, 51, 102));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("  Roll No");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(460, 220, 110, 40);

        jLabel4.setBackground(new java.awt.Color(0, 51, 102));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("  Mob No");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(460, 280, 110, 40);

        jLabel5.setBackground(new java.awt.Color(0, 51, 102));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("  Branch");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(460, 340, 110, 40);

        jLabel6.setBackground(new java.awt.Color(0, 51, 102));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("  Course");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(460, 400, 110, 40);

        txtName.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName);
        txtName.setBounds(651, 162, 240, 40);
        getContentPane().add(txtRollNo);
        txtRollNo.setBounds(650, 220, 240, 40);
        getContentPane().add(txtMobNo);
        txtMobNo.setBounds(650, 280, 240, 40);

        txtBranch.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtBranchActionPerformed(evt);
            }
        });
        getContentPane().add(txtBranch);
        txtBranch.setBounds(650, 340, 240, 40);
        getContentPane().add(txtCourse);
        txtCourse.setBounds(650, 400, 240, 40);

        btnSubmit.setBackground(new java.awt.Color(0, 51, 102));
        btnSubmit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.setOpaque(true);
        btnSubmit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit);
        btnSubmit.setBounds(580, 540, 150, 50);

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 51, 102));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(40, 50, 100, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Libb/background.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-3, -4, 1366, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBranchActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtBranchActionPerformed
    {//GEN-HEADEREND:event_txtBranchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBranchActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtNameActionPerformed
    {//GEN-HEADEREND:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSubmitActionPerformed
    {//GEN-HEADEREND:event_btnSubmitActionPerformed
        //Submit Button
        String Sname=txtName.getText();
        String rollNo= txtRollNo.getText();
        String course =txtCourse.getText();
        String branch= txtBranch.getText();
        String mob= txtMobNo.getText();

        if (!Pattern.matches("[a-zA-Z]*",Sname)) { //"+" "+"[a-zA-Z]+
        JOptionPane.showMessageDialog(this,"Invalid Name");
        txtName.setText("");
        txtName.requestFocus();  
        }
        else if (!Pattern.matches("[a-zA-Z]+",course)) { 
        JOptionPane.showMessageDialog(this,"Invalid Course Name");
        txtCourse.setText("");
        txtCourse.requestFocus(); 
        }
        else if (!Pattern.matches("[a-zA-Z]+",branch)) { 
        JOptionPane.showMessageDialog(this,"Invalid Branch Name");
        txtBranch.setText("");
        txtBranch.requestFocus();
        }
        else if (!Pattern.matches("[0-9]+",rollNo)) { 
        JOptionPane.showMessageDialog(this,"Invalid Roll No");
        txtRollNo.setText("");
        txtRollNo.requestFocus();  
        }
        else if (!Pattern.matches("[0-9]+",mob)) { 
        JOptionPane.showMessageDialog(this,"Invalid Moblie No");
        txtMobNo.setText("");
        txtMobNo.requestFocus();
        }
        else{
        try {
            par =con.prepareStatement("Insert into newstudent(SName,SRollNo,SCourse,SBranch,SMob)values(?,?,?,?,?)");
            par.setString(1,Sname);
            par.setString(2,rollNo);
            par.setString(3,course);
            par.setString(4,branch);
            par.setString(5,mob);
            int s=par.executeUpdate();
            if(s==1)
            {
                JOptionPane.showMessageDialog(this ," Details Submitted");
                txtName.setText("");
                txtRollNo.setText("");
                txtCourse.setText("");
                txtBranch.setText("");
                txtMobNo.setText("");
                txtName .requestFocus();
                StudentList();
            }
            else
            {
                JOptionPane.showMessageDialog(this ,"Errror");
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBackActionPerformed
    {//GEN-HEADEREND:event_btnBackActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static
            void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(NewStudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(NewStudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(NewStudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(NewStudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public
                    void run()
            {
                new NewStudentDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtBranch;
    private javax.swing.JTextField txtCourse;
    private javax.swing.JTextField txtMobNo;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRollNo;
    // End of variables declaration//GEN-END:variables
}
