
package Libb;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class StudentList extends javax.swing.JFrame
{
    Connection con;
    PreparedStatement par;
    ResultSet rs;
    public StudentList()
    {
        initComponents();
        Connect();
        StudentList();
    }
    public void Connect()
    {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pallavi","root","Dreams");   
        } 
        catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    public void StudentList(){
    int c;
        try {
            par=con.prepareStatement("select * from newstudent");
            rs=par.executeQuery();
            
            ResultSetMetaData rad =rs.getMetaData();
            c=rad.getColumnCount();
            
            DefaultTableModel d= (DefaultTableModel)jTable1.getModel();
            d.setRowCount(0);
            while(rs.next()){
            Vector v =new Vector();
            for(int i=1;i<=c;i++){
                v.add(rs.getString("SNo"));
                v.add(rs.getString("SName"));
                v.add(rs.getString("SRollNo"));
                v.add(rs.getString("SCourse"));
                v.add(rs.getString("SBranch"));
                v.add(rs.getString("SMob"));
            }
            d.addRow(v);
        }  
        } catch (SQLException ex) {
            
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtCourse = new javax.swing.JTextField();
        txtBranch = new javax.swing.JTextField();
        txtRollNo = new javax.swing.JTextField();
        txtMobNo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1518, 732));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 51, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  Student List ");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(600, 60, 240, 48);

        jLabel2.setBackground(new java.awt.Color(0, 51, 102));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" Student Name");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 150, 180, 50);

        jLabel3.setBackground(new java.awt.Color(0, 51, 102));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("       Course");
        jLabel3.setMaximumSize(new java.awt.Dimension(136, 32));
        jLabel3.setMinimumSize(new java.awt.Dimension(136, 32));
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(136, 32));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 220, 180, 50);

        jLabel4.setBackground(new java.awt.Color(0, 51, 102));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("       Branch");
        jLabel4.setMaximumSize(new java.awt.Dimension(136, 32));
        jLabel4.setMinimumSize(new java.awt.Dimension(136, 32));
        jLabel4.setOpaque(true);
        jLabel4.setPreferredSize(new java.awt.Dimension(136, 32));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 290, 180, 50);

        jLabel5.setBackground(new java.awt.Color(0, 51, 102));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("       Roll No");
        jLabel5.setMaximumSize(new java.awt.Dimension(136, 32));
        jLabel5.setMinimumSize(new java.awt.Dimension(136, 32));
        jLabel5.setOpaque(true);
        jLabel5.setPreferredSize(new java.awt.Dimension(136, 32));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(810, 146, 180, 50);

        jLabel6.setBackground(new java.awt.Color(0, 51, 102));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("      Mob No");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(810, 220, 180, 50);

        txtName.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName);
        txtName.setBounds(430, 150, 220, 50);

        txtCourse.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtCourseActionPerformed(evt);
            }
        });
        getContentPane().add(txtCourse);
        txtCourse.setBounds(430, 220, 220, 50);

        txtBranch.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtBranchActionPerformed(evt);
            }
        });
        getContentPane().add(txtBranch);
        txtBranch.setBounds(430, 290, 220, 50);

        txtRollNo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtRollNoActionPerformed(evt);
            }
        });
        getContentPane().add(txtRollNo);
        txtRollNo.setBounds(1030, 150, 220, 50);
        getContentPane().add(txtMobNo);
        txtMobNo.setBounds(1030, 220, 220, 50);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 102));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 50, 110, 30);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 102));
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(810, 300, 110, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String []
            {
                "Sno", "Student Name", "Roll No", "Course", "Branch", "Mob No"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(210, 380, 1040, 250);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBranchActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtBranchActionPerformed
    {//GEN-HEADEREND:event_txtBranchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBranchActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtNameActionPerformed
    {//GEN-HEADEREND:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtCourseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtCourseActionPerformed
    {//GEN-HEADEREND:event_txtCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseActionPerformed

    private void txtRollNoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtRollNoActionPerformed
    {//GEN-HEADEREND:event_txtRollNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRollNoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTable1MouseClicked
    {//GEN-HEADEREND:event_jTable1MouseClicked
         DefaultTableModel d1= (DefaultTableModel)jTable1.getModel();
         int selectIndex =jTable1.getSelectedRow();
         int SNo= Integer.parseInt( d1.getValueAt(selectIndex,0).toString());
        
         txtName.setText( d1.getValueAt(selectIndex,1).toString());
         txtRollNo.setText( d1.getValueAt(selectIndex,2).toString());
         txtCourse.setText( d1.getValueAt(selectIndex,3).toString());
         txtBranch.setText( d1.getValueAt(selectIndex,4).toString());
         txtMobNo.setText( d1.getValueAt(selectIndex,5).toString());
       
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel d1= (DefaultTableModel)jTable1.getModel();
        int selectIndex =jTable1.getSelectedRow();
        int SNo= Integer.parseInt( d1.getValueAt(selectIndex,0).toString());
        try {
            par =con.prepareStatement("Delete from NewStudent where SNo = ?");
            par.setInt(1,SNo); 
            int select =JOptionPane.showConfirmDialog(null, "Do you want to delete", "Confirm", JOptionPane.YES_NO_OPTION);
            if(select==JOptionPane.YES_OPTION)
            {  
            txtName.setText("");
            txtRollNo.setText("");
            txtCourse.setText("");
           
            txtBranch.setText("");
            txtMobNo.setText("");
             int s=par.executeUpdate();
            txtName.requestFocus();
            StudentList();
            }
            else{
            txtName.setText("");
            txtRollNo.setText("");
            txtCourse.setText("");
            txtBranch.setText("");
            txtMobNo.setText("");
               txtName.requestFocus();
            StudentList(); 
            }
        } catch (SQLException ex) {
           ex.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static
            void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(StudentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(StudentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(StudentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(StudentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run()
            {
                new StudentList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBranch;
    private javax.swing.JTextField txtCourse;
    private javax.swing.JTextField txtMobNo;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRollNo;
    // End of variables declaration//GEN-END:variables
}
